# Generated by Django 4.2.18 on 2025-02-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
