name: Checks

on:
  push:

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start Containers
        run: docker-compose up -d # Start all services in the background

      - name: Wait for Database
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until docker-compose exec -T db pg_isready -U devuser -d devdb; do
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Run Migrations
        run: docker-compose exec -T app sh -c "python manage.py migrate"

      - name: Run Tests
        run: docker-compose exec -T app sh -c "python manage.py test"

      - name: Run Linting
        run: docker-compose exec -T app sh -c "flake8"
